##Configuramos el servidor en donde se levantara el proyecto
server:
  port: 8091

springdoc:
  swagger_ui:
    path: /project-api-doc-ui.html

#Ruta donde se abrira
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    ##Dirrecion de la base de datos donde se almacena los datos
    url: jdbc:h2:file:~/data/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #Usuario y contraseña para ingresar al DB
    username: admin
    password: admin

  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comment: true
        format_sql: true
